In [ ]:
"""
Problem statement 1 : Write a Python program to multiply a M * N matrix by N * A matrix and create a real matrix product .
"""


import numpy as np

# I am creating a Function to input matrix of size M*N
def input_matrix(rows , cols):
  matrix = []
  for i in range(rows):
    rows = [float(x) for x in input().split()]
    matrix.append(rows)
  return np.array(matrix)

# Taking the values for M , N and A
M = int(input("Enter value M : "))
N = int(input("Enter value N : "))
A = int(input("Enter value A : "))

# giving input to the first matrix which is (M * N)
print("Enter values for the first array : ")
first_arr = input_matrix(M , N)

# giving input to the second matrix which is (N * A)
print("Enter values for the second array : ")
second_arr = input_matrix(N ,A)

#Calculating the dimensions of the two matrices.
a_rows, a_cols = first_arr.shape
b_rows, b_cols = second_arr.shape

# Checking if the dimensions are compatible for multiplication.
if a_cols != b_rows:
  raise ValueError("Matrices are not compatible for multiplication.")

# Calculating the dot product of the two matrices.
final_arr = np.dot(first_arr, second_arr)

# Printing the result.
print("\nFirst array:")
print(first_arr)
print("\nSecond array:")
print(second_arr)
print("\nDot product of two arrays:")
print(final_arr)




Enter value M : 5
Enter value N : 3
Enter value A : 2
Enter values for the first array : 
1 2 3
4 5 6
7 8 9 
9 8 7
6 5 4
Enter values for the second array : 
1 2 
3 4
5 6

First array:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [9. 8. 7.]
 [6. 5. 4.]]

Second array:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

Dot product of two arrays:
[[ 22.  28.]
 [ 49.  64.]
 [ 76. 100.]
 [ 68.  92.]
 [ 41.  56.]]


In [ ]:
""" Problem statement 2 : Wrie a NumPy program to check if each value of an array of your choice is composed of digits , lower case letters , and upper case letters only .
Hint : You can use isdigit() , islower() , and issuper() function .
"""
import numpy as np
import string

def check_composition(value):
  digit = any(char.isdigit() for char in value)
  lower = any(char.islower() for char in value)
  upper = any(char.upper() in string.ascii_uppercase for char in value)
  return digit and lower and upper

# creating the array :
arr = np.array(["Python","PHP","JS","Example","html5","5"])

# checking composition for each value in the array
final = np.vectorize(check_composition)(arr)

# Printing the original array and the result
print("Original Array : ")
print(arr)
print("\n Result (True if contains at least one digit , one lowercase letter , and one uppercase letter : )")
print(final)







Original Array : 
['Python' 'PHP' 'JS' 'Example' 'html5' '5']

 Result (True if contains at least one digit , one lowercase letter , and one uppercase letter : )
[False False False False  True False]


In [ ]:
""