In [ ]:
# Basic Concepts of OOPs
# What is a class and Instance

In [ ]:
# Define class Dog
class Dog:
    body_color = 'Brown' # attribute 1 of Dog
    eye_color = 'Black' # attribute 2 of Dog
    breed = 'Labrador' # attribute 3 of Dog

# Create Instance of Dog
bobby = Dog()

In [ ]:
bobby.body_color

'Brown'

In [ ]:
bobby.eye_color

'Black'

In [ ]:
bobby.breed

'Labrador'

In [ ]:
# Another instance of Dog is created
tommy = Dog()

In [ ]:
tommy.body_color, tommy.breed, tommy.eye_color

('Brown', 'Labrador', 'Black')

### Numpy

In [ ]:
'''
Why NumPy? Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python
lists. The array object in NumPy is called ndarray.

Used in:
Financial functions
Linear Algebra
Statistics
Polynomials
Sorting, searching etc.

Mainly used by institutions like - NASA and in Oceanography
http://ui.adsabs.harvard.edu/abs/2020Natur.585..357H/abstract

For example, in astronomy, NumPy was an important part of the software stack used
in the discovery of gravitational waves1 and in the first imaging of a black hole.
'''

In [ ]:
! pip install numpy

In [ ]:
L = list(range(100000))
print(type(L))
%timeit sum_val = sum(L)

<class 'list'>
290 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
import numpy as np
numpy_L = np.arange(100000)
%timeit sum_val = sum(numpy_L)

3.75 ms ± 5.82 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# Numpy arrays can be 1D or 2D

In [ ]:
import numpy as np

In [ ]:
# One - Dimensional Numpy Array

In [ ]:
x = np.array([100, 200, 300])
x

array([100, 200, 300])

In [ ]:
x.ndim

1

In [ ]:
x.shape

(3,)

In [ ]:
x.size

3

In [ ]:
# 2 - Dimensional Numpy Array

In [ ]:
x = np.array
([
    [100, 200, 300],
    [400, 500, 600]
])
x

array([[100, 200, 300],
       [400, 500, 600]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 3)

In [ ]:
x.size

6

In [ ]:
arr = np.zeros([2,3], dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr = np.ones([2,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Copy functions
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[0][1] = 200
arr

array([[  1, 200,   3],
       [  4,   5,   6]])

In [ ]:
arr[1,2] = 600
arr

array([[  1, 200,   3],
       [  4,   5, 600]])

In [ ]:
# Range functions : start, end + 1, 1
arr = np.arange(0, 20, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Linspace
arr = np.linspace(0, 10, 3)
arr

array([ 0.,  5., 10.])

In [ ]:
arr = np.linspace(0, 10, 4)
arr

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
# Elementwise operations

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr1 = np.arange(0, 5)
arr2 = np.arange(5,10)

In [ ]:
arr1

array([0, 1, 2, 3, 4])

In [ ]:
arr2

array([5, 6, 7, 8, 9])

In [ ]:
result = arr1 + arr2
result

array([ 5,  7,  9, 11, 13])

In [ ]:
arr1 * arr2

array([ 0,  6, 14, 24, 36])

In [ ]:
arr1 / arr2

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])