In [ ]:
# dimensions = r * c

In [ ]:
# Reshape Fn

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr = np.arange(16).reshape(2,8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
# Mult Fn
arr1 = np.arange(4).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [ ]:
arr1

array([[0, 1],
       [2, 3]])

In [ ]:
arr2

array([[5, 6],
       [7, 8]])

In [ ]:
arr1 * arr2

array([[ 0,  6],
       [14, 24]])

In [ ]:
# Matrix product / Dot product

In [ ]:
a = np.arange(4).reshape(2,2)
b = np.array([[11,12],[13,14]])

In [ ]:
a

array([[0, 1],
       [2, 3]])

In [ ]:
b

array([[11, 12],
       [13, 14]])

In [ ]:
np.dot(a , b)

array([[13, 14],
       [61, 66]])

In [ ]:
# Numpy Universal functions

In [ ]:
a = np.arange(4).reshape(2,2)
b = np.array([[11,12],[13,14]])

In [ ]:
np.add(a,b)

array([[11, 13],
       [15, 17]])

In [ ]:
np.subtract(a,b)

array([[-11, -11],
       [-11, -11]])

In [ ]:
np.divide(a,b)

array([[0.        , 0.08333333],
       [0.15384615, 0.21428571]])

In [ ]:
np.multiply(a,b)

array([[ 0, 12],
       [26, 42]])

In [ ]:
np.power(a,b)

array([[      0,       1],
       [   8192, 4782969]])

In [ ]:
# Sq-root
np.sqrt(a)

array([[0.        , 1.        ],
       [1.41421356, 1.73205081]])

In [ ]:
# Trignometric Functions

In [ ]:
a

array([[0, 1],
       [2, 3]])

In [ ]:
np.sin(a)

array([[0.        , 0.84147098],
       [0.90929743, 0.14112001]])

In [ ]:
np.cos(a)

array([[ 1.        ,  0.54030231],
       [-0.41614684, -0.9899925 ]])

In [ ]:
np.tan(a)

array([[ 0.        ,  1.55740772],
       [-2.18503986, -0.14254654]])

In [ ]:
# Converting from radians to degrees

In [ ]:
sin_60 = np.sin(60 * np.pi/180)
sin_60

0.8660254037844386

In [ ]:
sin_90 = np.sin(90 * np.pi/180)
sin_90

1.0

In [ ]:
# Comparison functions

In [ ]:
a

array([[0, 1],
       [2, 3]])

In [ ]:
b

array([[11, 12],
       [13, 14]])

In [ ]:
np.greater(a , b)

array([[False, False],
       [False, False]])

In [ ]:
np.greater_equal(a , b)

array([[False, False],
       [False, False]])

In [ ]:
np.less(a , b)

array([[ True,  True],
       [ True,  True]])

In [ ]:
np.equal(a , b)

array([[False, False],
       [False, False]])

In [ ]:
# Mod Function

In [ ]:
6 % 4

2

In [ ]:
x = np.mod(6 ,  4)
x

2

In [ ]:
# Log functions
np.log(1)

0.0

In [ ]:
# Hypotenuse

In [ ]:
b = 3
h = 4
np.hypot(b , h)

5.0

In [ ]:
# Aggregate functions

In [ ]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.sum()

45

In [ ]:
arr.min()

1

In [ ]:
arr.max()

9

In [ ]:
arr.mean() # Average

5.0

In [ ]:
# Indexing in numpy array

In [ ]:
arr = np.array([11, 12, 13, 14, 15])
arr

array([11, 12, 13, 14, 15])

In [ ]:
arr[1]

12

In [ ]:
arr[1 : ]

array([12, 13, 14, 15])

In [ ]:
arr[1 : 4]

array([12, 13, 14])

In [ ]:
arr[ :: -1]

array([15, 14, 13, 12, 11])

In [ ]:
arr[-1]

15

In [ ]:
arr = np.arange(11, 27).reshape(4,4)
arr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])

In [ ]:
# Returns complete row
arr[1]

array([15, 16, 17, 18])

In [ ]:
arr [ 1: , 1: ]

array([[16, 17, 18],
       [20, 21, 22],
       [24, 25, 26]])

In [ ]:
# Fancy Indexing
a = np.array([3,78,23,12,90,10,45,56])
a

array([ 3, 78, 23, 12, 90, 10, 45, 56])

In [ ]:
ind = np.array([[3,5], [2,4]])
a[ind]

array([[12, 10],
       [23, 90]])

In [ ]:
# Iterating thru the array
a

array([ 3, 78, 23, 12, 90, 10, 45, 56])

In [ ]:
# for those who work in projects that involve fourier transform / linear algebra
# they can use the nditer option along with order parameter
for i in np.nditer(a, order='K'):
    print(i)

3
78
23
12
90
10
45
56


In [ ]:
# for simple reading of the ndarray a standard for loop can be used
for i in a:
    print(i)

3
78
23
12
90
10
45
56


In [ ]:
# Transpose

In [ ]:
arr = np.arange(11, 27).reshape(4,4)
arr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])

In [ ]:
arr1 = np.transpose(arr)
arr1

array([[11, 15, 19, 23],
       [12, 16, 20, 24],
       [13, 17, 21, 25],
       [14, 18, 22, 26]])

In [ ]:
# Concatenate

In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[8, 10]])

In [ ]:
arr1

array([[1, 2],
       [3, 4]])

In [ ]:
arr2

array([[ 8, 10]])

In [ ]:
np.concatenate((arr1, arr2))

array([[ 1,  2],
       [ 3,  4],
       [ 8, 10]])

In [ ]:
# axis = 1 means concatenate as a column
# axis = 0 means concatenate as a row
np.concatenate((arr1, arr2.T), axis=1)

array([[ 1,  2,  8],
       [ 3,  4, 10]])

In [ ]:
# Splitting Array - split(), hsplit() and vsplit()

In [ ]:
a = np.array([3,78,23,12,90,10,45,56])
a

array([ 3, 78, 23, 12, 90, 10, 45, 56])

In [ ]:
a1, a2 = np.split(a, 2)

In [ ]:
a1

array([ 3, 78, 23, 12])

In [ ]:
a2

array([90, 10, 45, 56])

In [ ]:
arr = np.arange(11, 27).reshape(4,4)
arr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])

In [ ]:
arr1 , arr2, arr3, arr4 = np.hsplit(arr, 4)

In [ ]:
arr1

array([[11],
       [15],
       [19],
       [23]])

In [ ]:
arr2

array([[12],
       [16],
       [20],
       [24]])

In [ ]:
arr1 , arr2, arr3, arr4 = np.vsplit(arr, 4)
arr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])

In [ ]:
arr1

array([[11, 12, 13, 14]])

In [ ]:
arr2

array([[15, 16, 17, 18]])

In [ ]:
arr = np.arange(0, 25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a1, a2, a3, a4, a5 = np.hsplit(arr, 5)

In [ ]:
a1

array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

In [ ]:
# Saving the data to a file....

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.savetxt('file1.txt', arr, fmt='%0.1f')

In [ ]:
np.savetxt('file1.txt', arr, fmt='%d')

In [ ]:
import os
fp = open('file1.txt', 'r')
contents = fp.read()
print(contents)
fp.close()

0 1 2 3 4
5 6 7 8 9
10 11 12 13 14
15 16 17 18 19
20 21 22 23 24

