In [ ]:
l = list(range(100000))
print(type(l))
%timeit val = sum(l)

<class 'list'>
339 µs ± 4.23 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
# as we can see that list is taking too much time to process the values , where as the numpy process the data very easily within less time which is in milli seconds ..
import numpy as np
a = np.arange(100000)
%timeit sum_val = sum(a)

10.4 ms ± 3.12 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# arrays can be 1D or 2D .
import numpy as np
# one - dimensional Numpy array .
x = np.array([100,200,300])
print(x)

# to check the dimensions of the arrays . we have :
print("The array is ",x.ndim,"dimensional array")

# to check the shape of the array , we have :
print("The shape of the array is ",x.shape)


# to check the size of the array , we have :
print("The size of the arrays is : ",x.size)


# 2 - dimensional Numpy Array :

a = np.array([ [100,200,300],[400,500,600] ])
print("The second dimensional array is :\n ")
print(a)
print()
# if we want to see the dimension of this array we can use the same "ndim" .
print("The array is",a.ndim,"dimensional array..\n")

# if we want to see the size of the array , we can use :
print("The size of the arrys is : ",a.size)

# if we want to see the shape of the array , then :
# the shape is decided firstly through row then columns ...
print("The shape of the array is : ",a.shape)


[100 200 300]
The array is  1 dimensional array
The shape of the array is  (3,)
The size of the arrays is :  3
The second dimensional array is :
 
[[100 200 300]
 [400 500 600]]

The array is 2 dimensional array..

The size of the arrys is :  6
The shape of the array is :  (2, 3)


In [ ]:
# if we want the arrays filled with zeroes with specific shape , then we can do this :

import numpy as np

arr = np.zeros([2,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# if we want the arrays filled with ones with specific shape , then we can do this :
import numpy as np

arr = np.ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# by default the above arrays are in float we can convert them into integer too :
import numpy as np

arr = np.zeros([2,3],dtype=int)
print(arr)


[[0 0 0]
 [0 0 0]]


In [ ]:
# and for one's we have to do the same :
import numpy as np

arr = np.ones([2,3],dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]]


In [ ]:
# now we have copy function :
# we can copy one array into another like following :
import numpy as np

arr = np.array([ [100,200,300],[400,500,600]  ])
print(arr)
print()
copied = arr.copy()
print(copied)

# we can also access the elements through indexing and we can also change the elements too :
print(arr[0][0])
print(arr[1][2])
print()
# to change the elements within the array :
arr[0][0] = 50
print(arr)

[[100 200 300]
 [400 500 600]]

[[100 200 300]
 [400 500 600]]
100
600

[[ 50 200 300]
 [400 500 600]]


In [ ]:
# we can also generate the array through range function :
# for ex :
import numpy as np

arr = np.arange(0,20,2)
print("The array is : ",arr)

The array is :  [ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# Linspace function :
"""
numpy.linspace is a function that returns an array of evenly spaced numbers between two values.
The first argument is the start value, the second argument is the end value, and the third argument is the number of evenly spaced points between the two values.
"""
import numpy as np

arr = np.linspace(0,1,10)
print(arr)

print()
b = np.linspace(0 , 10 , 4)
print(b)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

[ 0.          3.33333333  6.66666667 10.        ]


In [ ]:
# Element wise operator :

import numpy as np

arr = np.arange(0,10)
print(arr)

# what if we want to add 2 in each element of the array once ? without using loops ..
# numpy helps us with this using only one line of code :

print("The addition by adding 2 in each element : ", arr + 2)
print()

# by doing same we can substract the elements from the above array as follows :

print("The Substraction by substracting 2 from each element : ",arr - 2)

# we can do the different arithmetic operations by doing the same ..



[0 1 2 3 4 5 6 7 8 9]
The addition by adding 2 in each element :  [ 2  3  4  5  6  7  8  9 10 11]

The Substraction by substracting 2 from each element :  [-2 -1  0  1  2  3  4  5  6  7]


In [ ]:
# we can also add the one or two arrays into one array :
import numpy as np

arr = np.arange(0,5)
arr_2 = np.arange(5,10)
print(arr)
print()
print(arr_2)
print()
arr_3 = arr + arr_2
print(arr_3)
print()
# we can also multiply the both the different arrays .
print(arr*arr_2)
print()
# We can also divide the arrays with the help of same method .
print(arr/arr_2)

[0 1 2 3 4]

[5 6 7 8 9]

[ 5  7  9 11 13]

[ 0  6 14 24 36]

[0.         0.16666667 0.28571429 0.375      0.44444444]


In [ ]:
# We all know that , dimensions = r * c
# Reshape function:
import numpy as np

arr = np.arange(16)
print(arr)
print()
print(arr.reshape(2,8))
print()
print(arr.reshape(8,2))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
# we can aslo multiply the 2-dimensional arrray .
arr1 = np.arange(4).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
print(arr1)
print()
print(arr2)
print()
print(arr1 * arr2)

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]

[[ 0  6]
 [14 24]]


In [ ]:
# Matrix product
import numpy as np

a = np.arange(4).reshape(2,2)
b = np.array([[11,12],[13,14]])
print(a)
print()
print(b)
print("The matrix product is : \n")
print(np.dot(a,b))

[[0 1]
 [2 3]]

[[11 12]
 [13 14]]
The matrix product is : 

[[13 14]
 [61 66]]


In [ ]:
0 * 11 + 1 * 13

13

In [ ]:
0 * 12 + 1 * 14

14

In [ ]:
2 * 11 + 3 * 13

61

In [ ]:
2 * 12 + 3 * 14

66

In [ ]:
# Numpy Universal Funcitons :
import numpy as np

a = np.arange(4).reshape(2,2)
b = np.array([[11,12],[13,14]])

print(np.add(a,b))
print()
print(np.subtract(a,b))
print()
print(np.divide(a,b))
print()
print(np.multiply(a,b))
print()
print(np.power(a,b))
print()
print("To calculate the square-root of individual arrays : ")
print(np.sqrt(a))
print()
print(np.sqrt(b))

[[11 13]
 [15 17]]

[[-11 -11]
 [-11 -11]]

[[0.         0.08333333]
 [0.15384615 0.21428571]]

[[ 0 12]
 [26 42]]

[[      0       1]
 [   8192 4782969]]

To calculate the square-root of individual arrays : 
[[0.         1.        ]
 [1.41421356 1.73205081]]

[[3.31662479 3.46410162]
 [3.60555128 3.74165739]]


In [ ]:
# Trignometric functions :
import numpy as np
arr = np.arange(4).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
print(arr)
print()
print(arr2)
print()
print(np.sin(arr))
print()
print(np.sin(arr2))

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]

[[0.         0.84147098]
 [0.90929743 0.14112001]]

[[-0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825]]


In [ ]:
# converting from radius to degrees :
sin_60 = np.sin(60 * np.pi / 180)
sin_60

0.8660254037844386

In [ ]:
sin_90 = np.sin(90 * np.pi / 180)
sin_90

1.0

In [ ]:
# Comparison functions :

import numpy as np

a = np.arange(4).reshape(2,2)
b = np.arange(11,15).reshape(2,2)
print()
print(a)
print()
print(b)
print()
print(np.greater(a,b))
print()
print(np.greater_equal(a,b))
print()
print(np.less(a,b))
print()
print(np.equal(a,b))






[[0 1]
 [2 3]]

[[11 12]
 [13 14]]

[[False False]
 [False False]]

[[False False]
 [False False]]

[[ True  True]
 [ True  True]]

[[False False]
 [False False]]


In [ ]:
# Mod funciton :
x = np.mod(6,4)
print(x)

2


In [ ]:
6%4

2

In [ ]:
# Log Funcitons :
np.log(1)

0.0

In [ ]:
# Hypotenuse  :
b = 3
h = 4
np.hypot(b,h)

5.0

In [ ]:
# Aggregate Funcitons :
import numpy as np

arr = np.arange(1,10)
print(arr)
print()
print(arr.sum())
print()
print(arr.min())
print()
print(arr.max())
print()
print(arr.min())
print()

[1 2 3 4 5 6 7 8 9]

45

1

9

1



In [ ]:
# Indexing in Numpy array :
arr = np.array([11,12,13,14,15])
print(arr)
arr[1]
print()
arr[1:]
arr[1 : 4]
arr[ : : -1]
arr[-1]

[11 12 13 14 15]



15

In [ ]:
import numpy as np

arr = np.arange(11,27).reshape(4,4)
print(arr)
# Returns complete row :
print()
print(arr[1])
print()
print(arr[1 : , 1 : ])

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]

[15 16 17 18]

[[16 17 18]
 [20 21 22]
 [24 25 26]]


In [ ]:
# Fancy indexing :

a  = np.array([3,78,23,12,90,10,45,56])
print(a)
print()
ind = np.array([[3,5],[2,4]]) # returns the elements from the index of above array 'a' .
print(a[ind])





[ 3 78 23 12 90 10 45 56]

[[12 10]
 [23 90]]


In [ ]:
# Iterating through arrays :
import numpy as np

arr = np.arange(20)
print(arr)
print()
# for those who work in projects that involve fourier transform or linear algebra
# they can use the nditer option along with order parameter .
for i in np.nditer(arr , order = "K"):
    print(i)

print()
# for simple reading of the ndarray a standard for loop can be used .
for i in arr:
  print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
# Transpose :
import numpy as np

arr = np.arange(11,27).reshape(4,4)
print(arr)
print()
arr1 = np.transpose(arr)
print(arr1)


[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]

[[11 15 19 23]
 [12 16 20 24]
 [13 17 21 25]
 [14 18 22 26]]


In [ ]:
# Condcatenate :
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[8,10]])
print(arr1)
print()
print(arr2)
print()
print(np.concatenate((arr1, arr2)))
# axis = 1 means concatenate as a column
# axis = 0 means concatenate as a row
print()
print(np.concatenate((arr1 , arr2.T),axis=1))

[[1 2]
 [3 4]]

[[ 8 10]]

[[ 1  2]
 [ 3  4]
 [ 8 10]]

[[ 1  2  8]
 [ 3  4 10]]


In [ ]:
# Splitting Array : split() , hsplit() and vsplit()
import numpy as np

a = np.array([3,78,23,12,90,10,45,56])
print(a)
print()
a1 , a2 = np.split(a,2)
print(a1)
print()
print(a2)


[ 3 78 23 12 90 10 45 56]

[ 3 78 23 12]

[90 10 45 56]


In [ ]:
import numpy as np

arr = np.arange(11,27).reshape(4,4)
print(arr)

arr1 , arr2 , arr3 , arr4 = np.hsplit(arr,4)
print(arr1)
print()
print(arr2)
print()
print(arr3)
print()
print(arr4)
print()
arr1 , arr2 , arr3 , arr4 = np.vsplit(arr,4)
print(arr1)
print()
print(arr2)
print()
print(arr3)
print()
print(arr4)



[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]
[[11]
 [15]
 [19]
 [23]]

[[12]
 [16]
 [20]
 [24]]

[[13]
 [17]
 [21]
 [25]]

[[14]
 [18]
 [22]
 [26]]

[[11 12 13 14]]

[[15 16 17 18]]

[[19 20 21 22]]

[[23 24 25 26]]
